### ISSUE TITLE
Sol prv

### ISSUE THREAD

**Issue by windswrold** [espresso-cash/espresso-cash-public#1369]
Using the same mnemonic phrase and okx web3 wallet, the addresses taken out are different, and the private key lengths are also different.

memo : know fresh kid distance swap upset ramp capable mask donor walnut sentence

okx prv :1cbA28aaabRshcg8YF85ARSXgC5G9W1B9MPgooGgQVzbTyMGcK95fbCrViugLWFbKEASWA5yrpkn86RWjLgJH6b
okx adds: 12j1biq4aqN7CpH9jamuRjd562yRgNxitpy1uPv4WxG3

**Comment by ookami-kb** [comment]
That's not a bug, it's expected behavior. From the same mnemonic phrase, you can generate multiple key pairs depending on the derivation path. Espresso Cash uses `m/44'/501'/0'/0'`, other wallets can use another path.
