### ISSUE TITLE
How to generate a private key for a wallet

### ISSUE THREAD

**Issue by zhangluya** [espresso-cash/espresso-cash-public#1424]
I was wondering how I should generate a private key for my wallet using the solana dart library？

`final Ed25519HDKeyPair wallet = await Wallet.fromSeedWithHdPath(seed: seed, hdPath: "m/44'/501'/0'/0'");`
<img width="1034" alt="code_prieview" src="https://github.com/espresso-cash/espresso-cash-public/assets/19799947/ddf86ca3-312a-40af-b4e4-db1fc01cced9">

I can't get my private key after I create a wallet using the code above?how can I export my private key for backing up my wallet?Please help me

**Comment by ookami-kb** [comment]
You can use `extract()` method:

```dart
final privateKey = (await wallet.extract()).bytes;
```

**Comment by zhangluya** [comment]
> You can use `extract()` method:
> 
> ```dart
> final privateKey = (await wallet.extract()).bytes;
> ```

thanks for your help, but when I try to import the Private Key obtained using the above method to my Phantom wallet, I get an error "incorrect format"
![photo_6178992664062573432_y](https://github.com/espresso-cash/espresso-cash-public/assets/19799947/828fcd32-5f08-4d42-b495-ec89dd084fc3)

**Comment by ookami-kb** [comment]
Phantom calls it private key but it actually expects private key + public key, you can get it like this:

```dart
import 'package:solana/base58.dart';
import 'package:solana/solana.dart';

Future<void> main() async {
  final account = await Ed25519HDKeyPair.random();
  final public = account.publicKey.bytes;
  final private = (await account.extract()).bytes;

  print(base58encode(private + public));
}
```

**Comment by cannon-lz** [comment]
> Phantom calls it private key but it actually expects private key + public key, you can get it like this:
> 
> ```dart
> import 'package:solana/base58.dart';
> import 'package:solana/solana.dart';
> 
> Future<void> main() async {
>   final account = await Ed25519HDKeyPair.random();
>   final public = account.publicKey.bytes;
>   final private = (await account.extract()).bytes;
> 
>   print(base58encode(private + public));
> }
> ```

thank you, this solved my issue
