### ISSUE TITLE
Testnet to Mainnet in solana_mobile_client

### ISSUE THREAD

**Issue by Airking26** [espresso-cash/espresso-cash-public#1525]
I cloned the project launched it and tested solana_mobile_client, it is working great.
But i change the rpcUrl in solana_mobile_client/example/lib/main to : 'https://api.mainnet-beta.solana.com' 
and websocketUrl to : 'wss://api.mainnet-beta.solana.com' and run the app with Phantom i have an error "Unable to connect the app, this app is trying to connect to Solana Testnet, but Solana Mainnet is selected".

Thank you

**Comment by Merculiar** [comment]
Hey, @Airking26 , have you changed cluster name to 'mainnet-beta'?
