### ISSUE TITLE
[Solana] Got error in "returnData" in meta while fetching transaction history

### ISSUE THREAD

**Issue by kishangohel** [espresso-cash/espresso-cash-public#1653]
solana: 0.31.0

**Describe the bug**
Failed

**To Reproduce**
1. Get Transaction history
`rpcClient
        .getTransactionsList(
      "8eyWJw3hoAitvASjdArXMBBqCriZN3KJNKnkYE5Nk2Lg",
      encoding: Encoding.jsonParsed,
      before: signature,
      limit: limit,
    )`
2. See error
`
#0      _$ReturnDataFromJson (package:solana/src/rpc/dto/return_data.g.dart:11:26)<…>
#1      new ReturnData.fromJson (package:solana/src/rpc/dto/return_data.dart:14:7)<…>
#2      _$MetaFromJson (package:solana/src/rpc/dto/meta.g.dart:37:24)<…>
#3      new Meta.fromJson (package:solana/src/rpc/dto/meta.dart:28:55)<…>
#4      _$TransactionDetailsFromJson (package:solana/src/rpc/dto/transaction_details.g.dart:16:18)<…>
#5      new TransactionDetails.fromJson (package:solana/src/rpc/dto/transaction_details.dart:20:7)<…>
#6      RpcClientExt.getMultipleTransactions.<anonymous closure> (package:solana/src/rpc/extension.dart:106:45)<…>
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)<…>
#8      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)<…>
#9      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:163:27)<…>
#10     new _List.of (dart:core-patch/array.dart:128:20)<…>
#11     new List.of (dart:core-patch/array_patch.dart:39:50)<…>
#12     ListIterable.toList (dart:_internal/iterable.dart:224:7)<…>
#13     RpcClientExt.getMultipleTransactions (package:solana/src/rpc/extension.dart:108:10)<…>
<asynchronous suspension><…>
`

**Expected behavior**
It should be decoded without exception

**Additional context**
It has some random token(Solana) received

**Comment by ookami-kb** [comment]
Fixed in version `0.31.0+1`
