### ISSUE TITLE
I need partial sign

### ISSUE THREAD

**Issue by napangelo** [espresso-cash/espresso-cash-public#631]
Hi,

I need to partially sign a transaction.

I have to do this thing with dart:
```
const transaction = new Transaction(... your instructions here ...);
const wireTransaction = transaction.serialize();

// send wireTransaction to backend to be signed
// on backend:
const latestBlockhash = await connection.getLatestBlockhash();
transaction.lastValidBlockHeight = latestBlockhash.lastValidBlockHeight;
transaction.recentBlockhash = latestBlockhash.blockhash;
transaction.feePayer = backendKey.publicKey;
transaction.partialSign(backendKey);
const wireTransactionToSendBack = transaction.serialize();

// send back wireTransactionToSendBack to frontend to be signed by user
// back on frontend:
transaction.partialSign(userKey); // or use a wallet adapter, most likely
const finalWireTransaction = transaction.serialize();
const signature = await connection.sendRawTransaction(finalWireTransaction);
```

Ref: https://solana-labs.github.io/solana-web3.js/classes/Transaction.html#partialSign

I didn't find the "partialSign" in your package.
How could I do this with your package?

Thanks
Angelo

**Comment by ookami-kb** [comment]
There's no built-in method for this, but you can create a partially signed tx manually by providing a "stub" signature.

Take a look at how we create a partially signed tx here: https://github.com/cryptoplease/cryptoplease-dart/blob/master/packages/cryptoplease_link/lib/src/payments/create_payment.dart

**Comment by AyushBherwani1998** [comment]
@ookami-kb the link gives 404, can you please provide a updated link to refer?
