### ISSUE TITLE
Implementation/use of the libraries

### ISSUE THREAD

**Issue by dcoldeira** [espresso-cash/espresso-cash-public#74]
Hi guys, just wondering how would you implement/use these libraries on Dart/Flutter? There isn't any example or guide, I will be more than happy to work on the documentation once somebody kindly sends me examples of how to use them and what you (currently) actually can do with them, if that makes sence? - Thanks

**Comment by ArjLab** [comment]
👍

**Comment by antoineherzog** [comment]
@iharob i believe this is the good time now as the library is quite complete, can you send some examples?

**Comment by Nithsua** [comment]
"Manually writing anchor compatible programs through a simple API". hey, can you guys provide a simple example for this. have been trying to do it all day but had no luck so far

**Comment by antoineherzog** [comment]
did you look at this file?

https://github.com/cryptoplease/cryptoplease-dart/blob/master/packages/solana/test/anchor_instruction_test.dart

**Comment by Nithsua** [comment]
Yeah, I was using it but having an issue with passing the accountData. I'm using getAccountInfo() to get account data but the data returned is of type BinaryAccountData and I'm unable to parse it to string or codeunits so that I can deserialize it with borsh

**Comment by antoineherzog** [comment]
@Nithsua I DM you on twitter
