### ISSUE TITLE
Connect wallet request is not showing when app is in background for Wallet Adapter

### ISSUE THREAD

**Issue by harshparikhfb** [espresso-cash/espresso-cash-public#848]
I've implemented wallet adapter functionality using https://pub.dev/packages/solana_mobile_wallet package, It successfully displays authentication dialog when app in not in background or when app is launched for the first time but I'm not able to get authentication status when app is in background, It always returns none status.

**To Reproduce**
1. Keep the application running in background
2. Go to any website which can connect to the wallet eg. https://www.orca.so
3. Click on connect wallet and it will display app to connect
4. When you click your app to connect It won't display authentication screen/dialog.

**Expected behavior**
Wallet app should listen authentication event even when app is in background like Phantom or Solfare did

**Comment by antoineherzog** [comment]
@harshparikhfb We have been able to reproduce the bug, we will investigate more now.
