### ISSUE TITLE
Does not work with latest cryptography module 2.2.0 and more

### ISSUE THREAD

**Issue by thomnico** [espresso-cash/espresso-cash-public#865]
**Describe the bug**
Solana depends on cryptography. It is now at version 2.4.0.

**To Reproduce**
1. Go to pubspec.yaml and depend on   cryptography: 2.2.0
3. Try to build

Get the following error:
/opt/homebrew/Caskroom/flutter/3.7.5/flutter/.pub-cache/hosted/pub.dev/solana-0.29.0/lib/src/crypto/ed25519_hd_keypair_data.dart:6:7: Error: The non-abstract class 'Ed25519HDKeyPairData' is missing implementations for these members:
 - KeyPair.destroy

 - KeyPair.hasBeenDestroyed
 - KeyPairData.copy
 - KeyPairData.publicKey
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class Ed25519HDKeyPairData implements KeyPairData {
      ^^^^^^^^^^^^^^^^^^^^
/opt/homebrew/Caskroom/flutter/3.7.5/flutter/.pub-cache/hosted/pub.dev/cryptography-2.2.0/lib/src/cryptography/key_pair.dart:35:8: Context: 'KeyPair.destroy' is defined here.
  void destroy() {
       ^^^^^^^
/opt/homebrew/Caskroom/flutter/3.7.5/flutter/.pub-cache/hosted/pub.dev/cryptography-2.2.0/lib/src/cryptography/key_pair.dart:26:12: Context: 'KeyPair.hasBeenDestroyed' is defined here.
  bool get hasBeenDestroyed => _hasBeenDestroyed;
           ^^^^^^^^^^^^^^^^
/opt/homebrew/Caskroom/flutter/3.7.5/flutter/.pub-cache/hosted/pub.dev/cryptography-2.2.0/lib/src/cryptography/key_pair.dart:64:15: Context: 'KeyPairData.copy' is defined here.
  KeyPairData copy();

              ^^^^
/opt/homebrew/Caskroom/flutter/3.7.5/flutter/.pub-cache/hosted/pub.dev/cryptography-2.2.0/lib/src/cryptography/key_pair.dart:61:17: Context: 'KeyPairData.publicKey' is defined here.
  PublicKey get publicKey;
                ^^^^^^^^^

**Expected behavior**
Solana module that can use the latest cryptography module and API.

**Additional context**
works with cryptography 2.1.0

**Comment by simon-vinova** [comment]
![image](https://user-images.githubusercontent.com/111500599/223651845-bde8fcce-a189-4c97-9996-229d27417599.png)
I update version of cryptography and it work with me
