### ISSUE TITLE
Key pair generated from seed phrase doesn't match to solana-keygen

### ISSUE THREAD

**Issue by roman-yerin** [espresso-cash/espresso-cash-public#939]
There's no any way to produce the same key pair using solana-keygen prompt:// and Ed25519HDKeyPair.fromMnemonic

The reason is here

```dart 
Future<Ed25519HDKeyPair> fromMnemonic(
  String mnemonic,
  { int account = 0,
  int change = 0 }
)
```

As you can see, both account and change has default value of 0, while according to docs

> If account and change are both null, then we derive the address that would be returned by using
> 
> `solana-keygen pubkey prompt://`
> 

So, if we omit both account and change while calling fromMnemonic, we actually get the key derived from m/44'/501'/0/0 and it doesn't match to m/44'/501' that solana-keygen uses. Actually, we can't even force account = null as it is an int type value not int?.

Although this is a bug, I am not sure if it should be fixed as it will probably affect people using this library and break backward compatibility. I suggest documentation changes to describe clearly this peculiarity.

**Comment by ookami-kb** [comment]
Hey, nice catch!

Yeah, it's a breaking change, but I think it still worths making it (we will just version it as breaking and add migration note) since in the long run this compatibility with the solana cli will bring more clarity.
