### ISSUE TITLE
dependant on old http version 

### ISSUE THREAD

**Issue by thomnico** [espresso-cash/espresso-cash-public#979]
**Describe the bug**
The http module version is now 1.0.0 starts to block other upgrades.

Please upgrade deps on HTTP module

**Comment by jainkrati** [comment]
+1, 
I am building [httpapp.librty.xyz](https://app.librty.xyz/#/initialRoute) using http 1.1.0 and in order to support Solana, I am dependent on this dependency upgrade. Please look into it at the earliest. 

I am also happy to submit a PR or work with you on this to share the load @rhbrunetto :)
