### ISSUE TITLE
Dart3 Support for the SDK

### ISSUE THREAD

**Issue by Killpit** [espresso-cash/espresso-cash-public#980]
Are there any Dart3 support for the SDK as most Flutter packages are Dart3 compatible.

**Comment by ookami-kb** [comment]
If you're talking about `solana` library, it's fully compatible with Dart 3.

**Comment by Killpit** [comment]
No, about all the libraries in the SDK

**Comment by ookami-kb** [comment]
They should be compatible as well.

**Comment by Killpit** [comment]
So, all the libraries support Dart3

**Comment by ookami-kb** [comment]
Yes, should be working with Dart 3.
